cmake_minimum_required (VERSION 3.14)

project(HeadFirst_DesignPatters_C++)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED  ON)
set(CMAKE_CXX_EXTENSIONS OFF)

add_subdirectory(chapters/chapter1)
add_subdirectory(chapters/chapter2)
add_subdirectory(chapters/chapter3)
add_subdirectory(chapters/chapter4)
add_subdirectory(chapters/chapter5)
add_subdirectory(chapters/chapter6)
add_subdirectory(chapters/chapter7)
add_subdirectory(chapters/chapter8)
